version: "3.9"

services:
  web:
    build: .
    container_name: "rss_scraper"
    ports:
      - "8000:8000"

    env_file: .env


    command: sh -c "python manage.py makemigrations &&
      python manage.py migrate &&
      python manage.py runserver 0.0.0.0:8000"


    volumes:
      - .:/usr/src/app


    depends_on:
      - db
      - cache

  celery_worker:
    build: .
    volumes:
     - .:/usr/src/app
    command:
      sh -c "celery -A rss_feed worker --loglevel=info"

    depends_on:
      - cache
    env_file:
      - .env

  db:
    image: postgres:latest
    ports:
    - "5432:5432"
    volumes:
    - dbv:/var/lib/postgresql/data
    env_file: .env

  cache:
    image: redis:latest
    volumes:
      - redisdata:/data


volumes:
  app:
  dbv:
  web-django:
  redisdata:


