# Generated by Django 3.2 on 2022-09-08 12:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('feed_subscription', '0004_feed'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('update_date', models.DateTimeField(auto_now=True)),
                ('title', models.TextField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('link', models.URLField()),
                ('pub_date', models.DateTimeField(blank=True, null=True)),
                ('is_read', models.BooleanField(default=False)),
                ('is_favorite', models.BooleanField(default=False)),
                ('is_bookmarked', models.BooleanField(default=False)),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feeds', related_query_name='feeds', to='feed_subscription.feedchannel')),
            ],
            options={
                'db_table': 'articles',
                'ordering': ['-create_date'],
            },
        ),
        migrations.DeleteModel(
            name='Feed',
        ),
    ]
