# Generated by Django 3.2 on 2022-09-12 13:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feed_subscription', '0006_feedchannel_last_update'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedchannel',
            name='deleted',
        ),
    ]
